### ISSUE TITLE
RSS feed showing duplicates in some feed readers

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#145]
It looks like one more bit of fallout from the #141 DDoS attacks and mitigations is a broken-for-some-users RSS feed:

```
$ curl https://www.jeffgeerling.com/blog.xml 2>/dev/null | grep "guid isPermaLink" | head -1
    <guid isPermaLink="false">3189 at http://www.jeffgeerling.com</guid>

$ curl https://www.jeffgeerling.com/blog.xml\?abcde 2>/dev/null | grep "guid isPermaLink" | head -1
    <guid isPermaLink="false">3189 at https://www.jeffgeerling.com</guid>
```

<img width="642" alt="156076227-5cef00bb-e8d8-4d57-abdd-72d90713d192" src="https://user-images.githubusercontent.com/481677/157296204-93385461-8ba7-4e18-83f8-86aacba77f5f.png">

Basically, there are cases where the URL returned in the `guid` has an http, and others where it's https. I'm not exactly sure how this is happening through Cloudflare (it never happened before)—but I'm guessing somehow Cloudflare is passing through http requests sometimes (even though I have "Full (strict)" enabled), and those are getting cached with the wrong guid's.

<img width="929" alt="Screen Shot 2022-03-08 at 11 12 18 AM" src="https://user-images.githubusercontent.com/481677/157289837-4445d1d3-17b0-426a-809e-adbfede30a41.png">

Internally in Nginx, I have redirects from http to https though, so I'm also not sure how the http could ever get through to a rendered feed...

**Comment by geerlingguy** [comment]
lol, of _course_ I've written my own blog post on the topic... [Configuring CloudFlare with Drupal 8 to protect the Pi Dramble](https://www.jeffgeerling.com/blog/2016/configuring-cloudflare-drupal-8-protect-pi-dramble).

**Comment by geerlingguy** [comment]
I just updated my Drupal config to use:

```
// Reverse proxy - Cloudflare.
$settings['reverse_proxy'] = TRUE;
$settings['reverse_proxy_addresses'] = array($_SERVER['REMOTE_ADDR']);
$settings['reverse_proxy_header'] = 'HTTP_CF_CONNECTING_IP';
```

We'll see if this fixes anything.

**Comment by geerlingguy** [comment]
Hmm... though `reverse_proxy_header` is deprecated / removed in Drupal 9. Grr.

**Comment by geerlingguy** [comment]
Nick Craver mentions I could enable HSTS on my domain (see https://twitter.com/Nick_Craver/status/1501248041004716043 and the rest of that thread) and it might help resolve it too. Though it'd be nice to make sure all the settings are correct up and down the stack.

**Comment by geerlingguy** [comment]
I might go with this sample code from [this comment](https://www.drupal.org/project/drupal/issues/3223280#comment-14236799):

```php
if (isset($_SERVER['HTTP_CF_CONNECTING_IP'])) {
  // If the CloudFlare header is contained in the X-Forwarded-For header, then
  // all IP addresses to the right of that entry are reverse-proxies, which are
  // additional to the value in $_SERVER['REMOTE_ADDR].
  // E.g. <client> --- <CDN> --- <Varnish> --- <drupal>.
  $client = $_SERVER['HTTP_CF_CONNECTING_IP'];
  $ips = explode(', ', $_SERVER['HTTP_X_FORWARDED_FOR']);
  if ($keys = array_keys($ips, $client)) {
    $position = end($keys);
    $reverseProxies = array_slice($ips, $position + 1);
    $reverseProxies[] = $_SERVER['REMOTE_ADDR'];

    $settings['reverse_proxy'] = TRUE;
    $settings['reverse_proxy_addresses'] = $reverseProxies;
  }
}
```

**Comment by geerlingguy** [comment]
Commit above has the code I added to live `local.settings.php`.

**Comment by ChrisLawther** [comment]
Provider of the `curl` output here, attempting to be helpful.

> I'm guessing somehow Cloudflare is passing through http requests sometimes 

> Internally in Nginx, I have redirects from http to https though, so I'm also not sure how the http could ever get through to a rendered feed...

Given that a reader _has_ seen a feed with plain http URLs in it, the redirect could be considered a **_good_** thing as it means attempts to read the full article page will succeed. Although the goal here is rightly not to publish those URLs to the feed in the first place.

As for how/why the feed has plain http URLs in it in the first place, I'm afraid I have no knowledge of Drupal, but in an attempt to rubber-duck towards a resolution:

(I'm not looking for answers here - I'm trying to find the right question to help you realise the cause)

As a curious observer, it seems there must be multiple Drupal instances at play, with varying senses of "self". How does a Drupal instance know it's identity? Does it get the scheme the same way? Are the nodes all definitely configured identically?

If that's what this is already trying to address:

> I just updated my Drupal config to use:
> 
> ```
> // Reverse proxy - Cloudflare.
> $settings['reverse_proxy'] = TRUE;
> $settings['reverse_proxy_addresses'] = array($_SERVER['REMOTE_ADDR']);
> $settings['reverse_proxy_header'] = 'HTTP_CF_CONNECTING_IP';
> ```
> 
> We'll see if this fixes anything.

... I can report that your latest article ("Rate limiting requests per IP address in Nginx") appears twice in my feed.

**Comment by ChrisLawther** [comment]
Oh, and I've just noticed the significance of the wording of the issue title:

> RSS feed showing duplicates if someone subscribed to http version

I have not subscribed to the http version. My feed reader is configured to fetch `http**s**://www.jeffgeerling.com/blog.xml` - it's always the same request from me, but the links in the returned content vary.

**Comment by geerlingguy** [comment]
@ChrisLawther - Okay, in that case I've fixed the title. I'm going to give it a couple days and we'll see if the next post hits the same issue. I don't have the time to dive into some CF requests on the server itself right now but that'll be the next step, to see where Drupal's getting it's http requests from.

**Comment by PH4NTOMiki** [comment]
> `cf-ray: 6e9dcdcd1b697747-LHR`
> v.s.
> `cf-ray: 6e9dce404e6b72e8-LHR`

CF-Ray header is like a request ID, LHR part means you are connecting to London data center (they are using nearest airport code) so in your case London Heathrow. 

report-to is for bot/spam protection.

**Comment by PH4NTOMiki** [comment]
From https://developers.cloudflare.com/fundamentals/get-started/http-request-headers/
The `CF-ray` header is a hashed value that encodes information about the data center and the visitor’s request.

And report-to reference https://support.cloudflare.com/hc/en-us/articles/360050691831-Understanding-Network-Error-Logging

**Comment by geerlingguy** [comment]
Someone else reported the issue today, too:

<img width="1030" alt="Screen Shot 2022-03-10 at 2 51 56 PM" src="https://user-images.githubusercontent.com/481677/157752330-e03ea02b-aa95-4a03-986b-8bd220034397.png">

This is from Miniflux.

**Comment by PH4NTOMiki** [comment]
> Nick Craver mentions I could enable HSTS on my domain (see https://twitter.com/Nick_Craver/status/1501248041004716043 and the rest of that thread) and it might help resolve it too.

@geerlingguy I think most of the RSS consumers don't respect HSTS.

**Comment by PH4NTOMiki** [comment]
I saw in your RSS feed that the link tag is to `http` variant and Drupal sets it here https://github.com/drupal/drupal/blob/515d10367bbe5cc158153a90e7960f92c2862745/core/modules/views/templates/views-view-rss.html.twig#L24 and that `link` variable is being populated by `Url::fromRoute('<front>')->setAbsolute()->toString()` here https://github.com/drupal/drupal/blob/515d10367bbe5cc158153a90e7960f92c2862745/core/modules/views/views.theme.inc#L888 
Can you try to do search-replace in your DB with something like PHPmyadmin, replace `http://www.jeffgeerling.com/` with `https://www.jeffgeerling.com/`

**Comment by PH4NTOMiki** [comment]
Do you have enabled HTTPS Always Use HTTPS in Cloudflare dashboard https://developers.cloudflare.com/ssl/edge-certificates/additional-options/always-use-https/#encrypt-all-visitor-traffic

**Comment by geerlingguy** [comment]
@PH4NTOMiki - Yes.

**Comment by PH4NTOMiki** [comment]
Do you have `fastcgi_param HTTPS on;` in nginx config?

**Comment by geerlingguy** [comment]
@PH4NTOMiki - I didn't, though I just forced it to `on` in `/etc/nginx/fastcgi_params`, restarted Nginx, and cleared caches on Cloudflare...

```
 21:25:42 ~ 
$ curl https://www.jeffgeerling.com/blog.xml 2>/dev/null | grep "guid isPermaLink" | head -1
    <guid isPermaLink="false">3191 at https://www.jeffgeerling.com</guid>

 21:25:43 ~ 
$ curl https://www.jeffgeerling.com/blog.xml\?asa 2>/dev/null | grep "guid isPermaLink" | head -1
    <guid isPermaLink="false">3191 at https://www.jeffgeerling.com</guid>
```

We'll see if that fix holds!

**Comment by PH4NTOMiki** [comment]
Fingers crossed, I'll make a script to test some URLs, hopefully they all come up as https. Will report back

**Comment by PH4NTOMiki** [comment]
> Fingers crossed, I'll make a script to test some URLs, hopefully they all come up as https. Will report back

I tested multiple routes and everyone came as https.

**Comment by geerlingguy** [comment]
Sounds like I owe @PH4NTOMiki a beer!

I'll close this for now—if anyone sees the duplicates again, please let me know!
