### ISSUE TITLE
Add warning on posts more than 10 years old

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#148]
I'd like to add a little info / warning bubble to the top of any post more than 10 years old (since my blog has a lot of old posts, some with outdated info that hasn't been updated and could be incorrect or misleading):

> This post is more than 10 years old. I do not delete posts, because even old information is still useful, but please know that some material on this page may be outdated or incorrect. Thanks!

**Comment by darkcactus1957** [comment]
I am guilty of archiving old posts. I for one, do not trust wayback machines. And Ii don;t trust magnetic tapes. Keep being you.

**Comment by geerlingguy** [comment]
@darkcactus1957 - Heh, I just like having it available. For technical posts, it can be a good point-in-time reference. For philosophical/life-related posts, it can be a good view into long-term changes in attitude or approach.

**Comment by geerlingguy** [comment]
I've added a block, but I need to pull it local, export it in config, and arrange for its appearance on nodes 10+ years old: https://www.jeffgeerling.com/admin/content/block/4

**Comment by geerlingguy** [comment]
<img width="1327" alt="Screenshot 2024-07-19 at 11 00 14 PM" src="https://github.com/user-attachments/assets/df831901-c966-49f0-b5e0-ed29dbd5267f">

About as good as I can muster using the built-in 'warning' CSS so I don't have to code up some display.
