### ISSUE TITLE
Test and benchmark other local development environments

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#18]
After episode 6, Oliver Davies mentioned the [Symfony Local Server](https://www.oliverdavies.uk/articles/running-drupal-with-symfony-local-server/), and I thought it might be time—especially since the live stream software eats my little MacBook Pro's CPU for lunch—to try out a faster local dev environment.

Because I'm one for data, I'd rather test things out with some 'official' timings, like how long it takes to install Drupal, to run a cache rebuild, and to migrate things.

So here's a table with some data:

| Dev Environment | Drupal install (drush) | 1st `/` page load (curl) | Cache rebuild (drush) |
| --- | --- | --- | --- |
| Current / custom Docker | 71.16s | 6.36s | 7.25s |
| Current / with NFS (#22) | 30.92s | 2.80s | 5.09s |
| Current / with bg-sync (#22) | 35.54s | 1.20s | 3.50s |
| Current / with docker-sync (#22) | 35.84s | 1.58s | 3.51s |
| [Symfony Local Server](https://symfony.com/doc/current/setup/symfony_server.html#setting-up-the-local-proxy) | 71.33s | 2.78s | 4.25s |
| [DDEV Local](https://ddev.readthedocs.io/en/stable/) | 63.24s | 4.16s | 9.20s |
| [Drupal VM](https://www.drupalvm.com) | 23.45s | 2.83s | 2.56s |

Commands run:

```
# Drupal install (drush)
time drush site:install minimal --db-url="mysql://drupal:$DRUPAL_DATABASE_PASSWORD@$DRUPAL_DATABASE_HOST/drupal" --site-name="Jeff Geerling" --existing-config -y

# Home page load (curl)
time curl http://localhost/

# Cache rebuild (drush)
time drush cr
```

**Comment by gitressa** [comment]
Thanks for the thorough bench-marking. I compared plain vanilla installs of Drupal 8 between ddev and Lando. They seem to perform almost at the same speed, except for `Lando start`, which takes 60 seconds, compared to ddev's 15 seconds.

**System**
- Ubuntu 18.04
- Composer 1.10.0
- Docker 19.03.8
- Lando v3.0.0-rc.23
- ddev v1.13.1

Get the Drupal 8 code with Composer 
```
$ time composer create-project drupal/recommended-project drupalddev
real  0m6,357s
```

# Lando
```
$ time lando init --source cwd --recipe drupal8 --webroot web --name drupallando
real  0m0,334s

$ time lando start
real  1m1,861s

$ time drush site:install --db-url=mysql://drupal8:drupal8@database/drupal8 -y
real  0m16,639s

$ time curl http://drupallando.lndo.site
real  0m1,452s

$ time drush cache:rebuild
real  0m2,719s
```

# ddev
```
$ time ddev config --project-type drupal8
real  0m0,040s

$ time ddev start
real  0m14,813s

$ time ddev exec drush site:install -y
real  0m15,121s

$ time curl http://drupalddev.ddev.site
real  0m1,325s

$ time ddev exec drush cache:rebuild
real  0m4,177s
```

**Comment by gitressa** [comment]
I just upgraded to the latest Lando [v3.0.0-aft.2](https://github.com/lando/lando/releases), and the first `lando start` of a new instance is 50% faster, down to half a minute. Just to clarify, I haven't timed the very first start after installing Lando itself, where PHP, MySQL and the rest of the software is downloaded. Here are the values for easier comparison, all times are in seconds:

Tool | First start | Start | site:install | 1st / page load (curl) | cache:rebuild
--- | --- | --- | --- | --- | ---
ddev 1.13.1 | 11.3 | 11.2 | 15.1 | 1.3 | 4.2
Lando v3.0.0-rc.23 | 61.9 | 7.6 | 16.6 | 1.5 | 2.7
Lando v3.0.0-aft.2 | 28.6 | 9.3 | 16.5 | 1.5 | 2.7

**Comment by geerlingguy** [comment]
@gitressa - Thanks so much for adding these details here! It may be time to revisit this project and update things again for 2020.

**Comment by gitressa** [comment]
You're welcome @geerlingguy :-) Revisiting and updating the bench-marking project would certainly be of great interest to me, and surely many others.

I noticed that the Lando script also downloads Drush 10, which will take around 20 seconds longer, compared to for example ddev:

```
# Install Drush, then install Drupal inside Lando.
lando composer require drush/drush
```

https://github.com/geerlingguy/drupal-the-fastest/blob/master/methods/lando.sh
https://github.com/geerlingguy/drupal-the-fastest/blob/master/methods/ddev-local.sh

Lando does come with Drush 8.3.2 out of the box, but perhaps Drush wasn't included, when the lando.sh script was initially created?

I have created a PR which updates Lando and removes Drush installation https://github.com/geerlingguy/drupal-the-fastest/pull/9.
