### ISSUE TITLE
`composer install` does not happen when running `docker-compose up`

### ISSUE THREAD

**Issue by pereorga** [geerlingguy/jeffgeerling-com#38]
Hi,

I followed the instructions in the README, and I needed to run `composer install` after running `docker-compose up -d`:

`docker-compose exec drupal bash -c 'composer install'`

(otherwise, Drupal did not install)

Thank you for this and for your videos, by the way!

**Comment by geerlingguy** [comment]
Ah, good point! You can do that on the host machine if you desire (assuming you have PHP and Composer already installed). I'll get the README updated.

**Comment by geerlingguy** [comment]
Fixed via above commit.
