### ISSUE TITLE
Migrate home page from Drupal 7 to Drupal 8

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/jeffgeerling-com#44]
> Matthew Turland (‪@elazar‬)
> 4/5/20, 7:23 PM
> ‪@geerlingguy‬ I know there's a link on the bottom of your web site's About page, but a more prominent link (maybe that includes the YouTube icon) on the landing page might also help.

After seeing the above tweet, I realized my current home page (pictured below) doesn't do a great job of pointing people towards places they can follow me (or getting any real CTA to happen):

<img width="1104" alt="Screen Shot 2020-04-06 at 10 39 35 AM" src="https://user-images.githubusercontent.com/481677/78576898-ecfcc180-77f2-11ea-9c1a-d2fdb44d30f6.png">

When I migrate the home page, I think I might do a few things:

1. Put maybe the latest 1, 2, or 3 blog posts (teaser) into the left column
2. Put a more condensed 'About' box in the top of the right column, linking out to About page at bottom
3. Maybe ditch the project listing entirely?
4. Add a 'follow me on XYZ' box after the About box (with YouTube, Twitter, and Instagram?)

**Comment by elazar** [comment]
1 isn't a bad idea; I personally just have my latest post take up most of the landing page.

I'd honestly suggest against 2 and 3 if you want to direct traffic to your projects, particularly those that generate income. If so, the fold is the best place to do it. Maybe add your YouTube channel as a link to that list of projects?

4 seems a reasonable choice.

**Comment by geerlingguy** [comment]
@elazar - Hmm... I think I'll have to test a few different methods out when working on migrating everything to Drupal 8 (might work on that next livestream episode tomorrow). I want it to be as simple as possible, too, and not a giant linkfest—however, people inbound to jeffgeerling.com might have an interest in finding one of 20 different ways to follow or support my work, so maybe not a bad idea either.

Right now 99% of the traffic on my site goes to an individual blog post page anyways, so optimizing the home page for someone who might've clicked there intentionally and wants to find ways to follow/support might not be bad.

**Comment by geerlingguy** [comment]
I definitely don't want to go down the path of these kind of full-page-nothing-useful sites https://www.listenmoneymatters.com/best-personal-websites/

**Comment by geerlingguy** [comment]
I honestly like the refreshing feel of something like this; good ratio of links:content, and the layout can flow nicely on mobile too:

![image](https://user-images.githubusercontent.com/481677/78594170-6bfef380-780d-11ea-828b-5f06737f003d.png)

I think it's sad that now goes to https://rationalreminder.ca/blog, which is a lot more of the "boring giant generic image at top followed by fancy but also boring list of titles" format for the posts.

**Comment by geerlingguy** [comment]
Since the home page migration is complete, I've moved the _revamp_ portion of this issue over to a new issue, #47
